# This file was generated by GoReleaser. DO NOT EDIT.
class BinqGh < Formula
  desc "Wrapper CLI for binq with GitHub features"
  homepage ""
  version "0.3.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/binqry/binq-gh/releases/download/v0.3.1/binq-gh_0.3.1_darwin_amd64.zip"
    sha256 "fb304d4bd3aa4950d2afa55bf4c457fc2063ec8553fb757e920233419e4155b9"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/binqry/binq-gh/releases/download/v0.3.1/binq-gh_0.3.1_linux_amd64.zip"
      sha256 "314a2a56b712f74af26b3a01a60af96752a881c5d741441416226288d233c055"
    end
  end

  def install
    bin.install "binq-gh"
  end

  test do
    system "#{bin}/binq-gh", '--version'
  end
end
